import React from "react";

//Functional component take props as an argument
const Home = props => {
  return (
    <div>
      <p />
      <div class="list-group">
        <a
          href="#"
          class="list-group-item list-group-item-action flex-column align-items-start active"
        >
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">List group item heading</h5>
            <small>Main</small>
          </div>
          <p class="mb-1">
            This is a simple ether wallet, designed to be safe, straight forward
            and user friendly. This wallet does not save your private keys into
            any backend server.
          </p>
          <small>Give a try!.</small>
        </a>
        <a
          href="#"
          class="list-group-item list-group-item-action flex-column align-items-start"
        >
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">View Balance</h5>
            <small class="text-muted">feature</small>
          </div>
          <p class="mb-1">
            The View Balance feature enable you to query a balance of your valid
            ethereum public address, even addresses not generated by this
            wallet.
          </p>
          <small class="text-muted">Donec id elit non mi porta.</small>
        </a>
        <a
          href="#"
          class="list-group-item list-group-item-action flex-column align-items-start"
        >
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Create Wallet</h5>
            <small class="text-muted">Wallet feature</small>
          </div>
          <p class="mb-1">
            Before Send or Receive ether, you need to Create a Wallet. This will
            provide you with a public address and a private key. Print/save your
            private key and place it in a safe storage, as you will need it to
            sign Send Ether transactions.
          </p>
          <small class="text-muted">Donec id elit non mi porta.</small>
        </a>
      </div>

      <div class="card">
        <div class="card-header">Quote</div>
        <div class="card-body">
          <blockquote class="blockquote mb-0">
            <p>
              This is a simple ether wallet, designed to be straight forward and
              user friendly. This wallet does NOT save your private keys into
              any backend server.
              <p>Getting Started</p>
              <ul>
                <li>
                  The View Balance feature enable you to query a balance of your
                  valid ethereum public address, even addresses not generated by
                  this wallet.
                </li>
                <li>
                  Before Send or Receive ether, you need to Create a Wallet.
                  This will provide you with a public address and a private key.
                  Print/save your private key and place it in a safe storage, as
                  you will need it to sign Send Ether transactions.
                </li>
              </ul>
            </p>
            <footer class="blockquote-footer">
              Someone famous in <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>
        </div>
      </div>
    </div>
  );
};

export default Home;
